import { MISSION_STATUS } from '../../constants/missionStatus';
import { WorkflowRules } from './workflow.engine';

export const missionWorkflow: WorkflowRules = {
  [MISSION_STATUS.PLANNED]: [
    MISSION_STATUS.READY,
    MISSION_STATUS.CANCELLED
  ],

  [MISSION_STATUS.READY]: [
    MISSION_STATUS.IN_PROGRESS,
    MISSION_STATUS.PLANNED,      // 🔁 retour arrière
    MISSION_STATUS.CANCELLED
  ],

  [MISSION_STATUS.IN_PROGRESS]: [
    MISSION_STATUS.UNDER_REVIEW,
    MISSION_STATUS.READY,        // 🔁 retour cadrage
    MISSION_STATUS.CANCELLED
  ],

  [MISSION_STATUS.UNDER_REVIEW]: [
    MISSION_STATUS.APPROVED,
    MISSION_STATUS.IN_PROGRESS,  // 🔁 correction
    MISSION_STATUS.CANCELLED
  ],

  [MISSION_STATUS.APPROVED]: [
    MISSION_STATUS.CLOSED
  ],

  [MISSION_STATUS.CLOSED]: [],

  [MISSION_STATUS.CANCELLED]: []
};
